services:
  postgres:
    image: postgres:17.4-alpine3.21
    cap_drop:
      - NET_RAW
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: glcd
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      start_period: 30s
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgAdmin:
    container_name: pgadmin
    image: elestio/pgadmin:latest
    ports:
      - "8800:80"
    cap_drop:
      - NET_RAW
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    healthcheck:
      test: [ "CMD", "wget", "-0", "-", "http://localhost:8800/misc/ping" ]
      interval: 5s
      timeout: 5s
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data:
